[package]
name = "driver_core"
version = "0.1.0"
description = "Core drivers for the OS, such as GPIO stuff"
authors = ["Kishan <kishansambhi@hotmail.co.uk>"]
edition = "2018"

[dependencies]
register = "0.2.1"
